config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    member do
      put "/like" => "cars#like"
    end
  end

  get 'static/welcome'
  resources :cars
  root 'static#welcome'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception 
 
    def current_user 
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]


    end

    helper_method :current_user 
    
    def authenticate_user! 
         redirect_to '/login' unless current_user 
         
        
    end 
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    
    
    if current_user
      
      @cars = Car.all
      render "index.html.erb"
     
    else 
      flash[:warning] = "You must be logged in to see this page"
      redirect_to '/login'
      
    end

    
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def like
    respond_to :js, :html, :json
    
    @car = Car.find(params[:id])
    if params[:format] == 'like'
      @post.liked_by current_user
    elsif params[:format] == 'unlike'
      @post.unliked_by current_user
    end
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :model, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
    user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:success] = 'Successfully Logged In!'
        redirect_to '/cars'
        
  
        else
        flash[:warning] = "Invalid Username or Password"
        redirect_to '/login'
        end
    end
    
    def destroy
     session[:user_id] = nil
     flash[:success] = "Successfully Logged Out!"
     redirect_to '/cars'
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        user = User.new(
            name: params[:name],
            email: params[:email],
            password: params[:password],
            password_confirmation: params[:password_confirmation]
            )
        if user.save 
            session[:user_id] = user.id 
            flash[:success] = "Successfully Created User!"
            redirect_to '/cars'
        else 
            flash[:warning] = "Invalid Email or Password"
            redirect_to '/signup'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cars</h2>

   <div id="cardContainer">     
    <% @cars.each do |car| %>
      <div id="cards">
        <div id="brand"><%= car.brand %></div>
        <div id="model"><%= car.model %></div>
        <div><%= link_to (image_tag car.url, :class=> "carImage" ), car  %></div>
        <div><%= link_to 'Show ', car %><%= link_to 'Edit ', edit_car_path(car) %><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>
  
</div>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/like.js.erb
$('.preached-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like_count')
    .html('<%= @car.get_likes.size %> &#128591');
    $(this).closest('.preached-btn').html('Preach');
});

$('.preached-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like_count')
    .html('<%= @car.get_likes.size %> &#128591');
    $(this).closest('.preached-btn').html('Preached');
});

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>
<div id="cont">
  <%# <div id="brand"><strong>Brand:</strong></div> %>
  <div id="brand"><%= @car.brand %></div>


  <%# <div id="brand"><strong>Model:</strong></div> %>
  <div id="model"> <%= @car.model %></div>
</div>
<p>
  <%= image_tag @car.url, :class=> 'carImage2' %>
</p>

<span class='parent-likes'>
  <span class="like-count" <%=@car.id%>'>
    <%= @car.get_likes.size %> &#128591
  </span>

  <a>
    <% if current_user.liked? @car %>
      <div> <%= link_to like_car_path(@car, 'unlike'), class: "preached-btn",
      method: :put, remote: :true do %> Preached </div>
    <% end%>
    <% else %>
      <div> <%= link_to like_car_path(@car, 'like'), class: "preach-btn",
      method: :put, remote: :true do %> Preach </div>
    <% end%>
    <% end%>
  <a>
</span>

<%# <%= link_to 'Edit', edit_car_path(@car) %> 
<%= link_to 'Back', cars_path, id:"linktext"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Zen+Dots&display=swap'%>
  </head>

  <body>

    <header>
    
      <div id="logo">
        <div><%= link_to "Best SUV", root_path, id: "logo1" %></div>
        <div><%= link_to "2021", root_path, id: "logo2" %></div>
        
      </div>

      <div id="loginout"> 
        <% if current_user %>
          <div id="login">Logged in as <%= current_user.email %></div>
          <div><%= link_to "Logout", logout_path, id: "logout" %></div>
        <% else %>
          <div id="register"><%= button_to "Login or SignUp", '/login', class: "myButton" %></div>
        <% end %>

      </div>


    </header>

   

    <div id="container">
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h2> Create Account</h2>
<%=form_tag "/users", method: :post do%>
 <div>
  <%= label_tag :name%>
  <%= text_field_tag :name%>
 </div>
 <div>
  <%= label_tag :email%>
  <%= text_field_tag :email%>
 </div>
 <div>
  <%= label_tag :password%>
  <%= password_field_tag :password%>
 </div>
 <div>
  <%= label_tag :password_confirmation%>
  <%= password_field_tag :password_confirmation%>
 </div>
 
<%= submit_tag "Sign Up", class: "btn btn-default"%>
<%end%>



<h1>Login</h1>
<%= form_tag '/login', method: :post do %>
 <div>
  <%= label_tag :email %>
  <%= text_field_tag :email%>
 </div>
 <div>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
 </div>
  <%= submit_tag "Submit" %>
<%end%>